// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYk4FoCJy2iU0Ta9RL-2uTijr42p-45qE',
    appId: '1:21784477377:web:1cae864b3980ba86bf5e40',
    messagingSenderId: '21784477377',
    projectId: 'task-app-d3f4b',
    authDomain: 'task-app-d3f4b.firebaseapp.com',
    storageBucket: 'task-app-d3f4b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgXBP-sNSHnc7VHpEjMQ0vuDnSMX6cXaM',
    appId: '1:21784477377:android:2aa8c97025bce2d6bf5e40',
    messagingSenderId: '21784477377',
    projectId: 'task-app-d3f4b',
    storageBucket: 'task-app-d3f4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8pU0s_ZuDVGgf9HVQBDk_cWvs_a9r5ZA',
    appId: '1:21784477377:ios:56d0b4a8d2d8c946bf5e40',
    messagingSenderId: '21784477377',
    projectId: 'task-app-d3f4b',
    storageBucket: 'task-app-d3f4b.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8pU0s_ZuDVGgf9HVQBDk_cWvs_a9r5ZA',
    appId: '1:21784477377:ios:56d0b4a8d2d8c946bf5e40',
    messagingSenderId: '21784477377',
    projectId: 'task-app-d3f4b',
    storageBucket: 'task-app-d3f4b.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYk4FoCJy2iU0Ta9RL-2uTijr42p-45qE',
    appId: '1:21784477377:web:3dbb9a197794ffbdbf5e40',
    messagingSenderId: '21784477377',
    projectId: 'task-app-d3f4b',
    authDomain: 'task-app-d3f4b.firebaseapp.com',
    storageBucket: 'task-app-d3f4b.firebasestorage.app',
  );
}
