// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSRErdxNxhHiJXOWCFlejLSL9121MQoPs',
    appId: '1:110829206631:web:2bfba7c805a8a44290a8c2',
    messagingSenderId: '110829206631',
    projectId: 'sellphy',
    authDomain: 'sellphy.firebaseapp.com',
    storageBucket: 'sellphy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3XKSfOz6RjGgMxH721JvExsq-LHZMxts',
    appId: '1:110829206631:android:cb659de1a779213290a8c2',
    messagingSenderId: '110829206631',
    projectId: 'sellphy',
    storageBucket: 'sellphy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9rKOqi3UGxjew_S8H0ezq3_w9LvcdKXc',
    appId: '1:110829206631:ios:31e1279826ba009690a8c2',
    messagingSenderId: '110829206631',
    projectId: 'sellphy',
    storageBucket: 'sellphy.firebasestorage.app',
    iosBundleId: 'com.example.sellphy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9rKOqi3UGxjew_S8H0ezq3_w9LvcdKXc',
    appId: '1:110829206631:ios:31e1279826ba009690a8c2',
    messagingSenderId: '110829206631',
    projectId: 'sellphy',
    storageBucket: 'sellphy.firebasestorage.app',
    iosBundleId: 'com.example.sellphy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSRErdxNxhHiJXOWCFlejLSL9121MQoPs',
    appId: '1:110829206631:web:7b9718040328dbbd90a8c2',
    messagingSenderId: '110829206631',
    projectId: 'sellphy',
    authDomain: 'sellphy.firebaseapp.com',
    storageBucket: 'sellphy.firebasestorage.app',
  );
}
